repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.2.0
        hooks:
            #- id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-docstring-first
            -   id: check-json
            -   id: check-yaml
            # - id: debug-statements
            -   id: name-tests-test
            -   id: detect-private-key
            -   id: detect-aws-credentials
            # - id: requirements-txt-fixer
            # - id: double-quote-string-fixer
