#!/bin/bash
set -e

JAVA_HOME="${JAVA_HOME:-/usr/lib/jvm/java-17-openjdk-amd64}"
export JAVA_HOME
CLASSPATH="/opt/plantuml/jlatexmath.jar:/opt/plantuml/plantuml.jar:/opt/plantuml/batik-all.jar"
export CLASSPATH
${JAVA_HOME}/bin/java -classpath "${CLASSPATH}" net.sourceforge.plantuml.Run $@

exit $?
