---
name: docker-image-build-action

on:
    push:
        tags:
            - '*.*.*'
    pull_request:
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write

        steps:
            - name: Check out the repo
              uses: actions/checkout@v6
              with:
                fetch-depth: 1

            - name: Log in to Docker Hub
              uses: docker/login-action@v4
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Login to DockerHub
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v4
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            - id: setup-buildx
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4


            - id: docker_image_build_push_to_ghcr
              name: Build app, build docker image and Push image to ghcr.io
              uses: docker/build-push-action@v7
              with:
                  platforms: linux/amd64
                  context: .
                  file: ./Dockerfile
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                      docker.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
                      docker.io/${{ env.IMAGE_NAME }}:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  build-args: |
                      VERSION=${{ github.ref_name }}
                      COMMIT_SHA=${{ github.sha }}

            - id: docker_image_digest
              name: Show Docker Image digest
              run: echo ${{ steps.docker_image_build_push_to_ghcr.outputs.digest }}

            - name: Generate artifact attestation
              if: github.event_name != 'pull_request' && steps.docker_image_build_push_to_ghcr.outputs.digest != ''
              uses: actions/attest@v4
              with:
                  subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  subject-digest: ${{ steps.docker_image_build_push_to_ghcr.outputs.digest }}
                  push-to-registry: true
